{
	"Pre-written Code": {
		"prefix": "imrvrs",
		"body": [
		  "/*",
		  "* Author: Aayush Tyagi",
		  "* Created: $CURRENT_DATE-$CURRENT_MONTH-$CURRENT_YEAR $CURRENT_HOUR:$CURRENT_MINUTE:$CURRENT_SECOND",
		  "* Language: C++",
		  "*/",
		  "#include<iostream>",
		  "#include<cmath>",
		  "#include<cstring>",
		  "#include<climits>",
		  "#include<algorithm>",
		  "#include<vector>",
		  "#include<deque>",
		  "#include<queue>",
		  "#include<stack>",
		  "#include<list>",
		  "#include<set>",
		  "#include<unordered_set>",
		  "#include<map>",
		  "//#include<unordered_map>",
		  "#include<tr1/unordered_map>",
		  "",
		  "using namespace std;",
		  "using namespace std::tr1;",
		  "",		
		  "typedef long long ll;",
		  "typedef long double ld;",
		  "typedef pair<int,int> p32;",
		  "typedef pair<ll,ll> p64;",
		  "typedef vector<int> v32;",
		  "typedef vector<ll> v64;",
		  "",
		  "ll MOD7 = 1e9+7;",
		  "ll MOD9 = 1e9+9;",
		  "//ld PI = M_PI;",
		  "",
		  "#define pb push_back",
		  "#define mp make_pair",
		  "#define rep(i,s,e) for(int i=s;i<=e;i++)",
		  "#define brep(i,s,e) for(int i=s;i>=e;i--)",
		  "#define all(x) x.begin(),x.end()",
		  "#define mem(x,y) memset(x,y,sizeof(x))",
		  "#define ones __builtin_popcount",
			
		  "#define fast std::ios::sync_with_stdio(false); cin.tie(NULL); cout.tie(NULL)",
		  "",
		  "int main()",
		  "{",
		  "    //fast;",
		  "    ll t;",
		  "    cin>>t;",
		  "    while(t--)",
		  "    {",
		  "        $2",
		  "    }",
		  "}",
		],
		"description": "Writes pre-written code automatically"
	  },
		"Small Pre-written Code": {
		"prefix": "haha",
		"body": [
		  "/*",
		  "* Author: Aayush Tyagi",
		  "* Created: $CURRENT_DATE-$CURRENT_MONTH-$CURRENT_YEAR $CURRENT_HOUR:$CURRENT_MINUTE:$CURRENT_SECOND",
		  "* Language: C++",
		  "*/",
		  "#include<iostream>",
		  "using namespace std;",
		  "int main()",
		  "{",
		  "    //fast;",
		  "    $2",
		  "}",
		],
		"description": "Writes pre-written code automatically"
	  }
}
